[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
upload_port = COM7      ; <-- replace with the COM number Device Manager shows
monitor_port = COM7

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library @^3.0.2
    ;  huskylens/HuskyLens @^1.0.0
    bblanchon/ArduinoJson @ ^7.0.0
    https://github.com/HuskyLens/HUSKYLENSArduino/archive/refs/heads/master.zip

build_flags =
    -Wno-return-type
    -Wno-incompatible-pointer-types