[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_extra_dirs = 3. Library


monitor_speed = 9600
lib_deps =
  z3t0/IRremote@^3.9.0
  dfrobot/DFRobotDFPlayerMini@^1.0.6
  knolleary/PubSubClient